{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: user
  source:
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: HEAD
    path: "helm-charts/infra/{{ $app.name }}"
  destination:
    namespace: {{ $app.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true       # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true    # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ). When disabled and resources are changed only in kubernetes, resources will be marked out of sync. If set, this will automatically heal all child-applications, even when they are temporarily marked as non-self-healing.
      allowEmpty: true  # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - Validate=true                      # Disables resource validation (equivalent to 'kubectl apply --validate=false'). Default: true
      - ApplyOutOfSyncOnly=true            # If the sync option is set Argo CD will sync only out-of-sync resources. Default: false
      - PrunePropagationPolicy=foreground  # Supported policies are background, foreground and orphan. Default: foreground
      - PruneLast=false                    # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation. Default: false
      - Replace=false                      # If the sync option is set the Argo CD will use kubectl replace or kubectl create command to apply changes. Default: false
      - CreateNamespace=true               # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster. Default: false
    retry:
      limit: 5           # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s     # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2        # a factor to multiply the base duration after each failed retry
        maxDuration: 3m  # the maximum amount of time allowed for the backoff strategy
{{- end }}
